[project]
name = "seqme-reproducibility"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.6",
    "matplotlib>=3.10.8",
    "nbconvert>=7.17.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
case1 = [
    "seqme[aa_descriptors, esm2]>=0.5.0",
]
case2 = [
    "seqme[rnafm]>=0.5.0",
]
